housegui = guiCreateWindow(334,180,309,337,"Home",false)
infolabel = guiCreateLabel(15,30,276,15,"The home system by mR|TurboCow",false,housegui)
guiLabelSetColor(infolabel,255, 200, 0)
guiLabelSetVerticalAlign(infolabel,"center")
guiLabelSetHorizontalAlign(infolabel,"center",false)
guiSetFont(infolabel,"default-bold-small")
homiePicture = guiCreateStaticImage(20,54,106,80,"home.jpeg",false,housegui)
ownerLabel2 = guiCreateLabel(179,54,100,16,"---",false,housegui)
guiSetAlpha(ownerLabel2,1)
guiLabelSetColor(ownerLabel2,225,225,225)
guiLabelSetVerticalAlign(ownerLabel2,"top")
guiLabelSetHorizontalAlign(ownerLabel2,"left",false)
guiSetFont(ownerLabel2,"default-bold-small")
numberLabel = guiCreateLabel(137,90,50,16,"Number:",false,housegui)
guiLabelSetColor(numberLabel,255,200,0)
guiLabelSetVerticalAlign(numberLabel,"top")
guiLabelSetHorizontalAlign(numberLabel,"left",false)
guiSetFont(numberLabel,"default-bold-small")
priceLabel = guiCreateLabel(137,72,41,16,"Price: $",false,housegui)
guiLabelSetColor(priceLabel,255,200,0)
guiLabelSetVerticalAlign(priceLabel,"top")
guiLabelSetHorizontalAlign(priceLabel,"left",false)
guiSetFont(priceLabel,"default-bold-small")
streetLabel = guiCreateLabel(137,107,39,16,"Street:",false,housegui)
guiLabelSetColor(streetLabel,255,200,0)
guiLabelSetVerticalAlign(streetLabel,"top")
guiLabelSetHorizontalAlign(streetLabel,"left",false)
guiSetFont(streetLabel,"default-bold-small")
ownerLabel = guiCreateLabel(137,54,40,16,"Owner:",false,housegui)
guiLabelSetColor(ownerLabel,255,200,0)
guiLabelSetVerticalAlign(ownerLabel,"top")
guiLabelSetHorizontalAlign(ownerLabel,"left",false)
guiSetFont(ownerLabel,"default-bold-small")
priceLabel2 = guiCreateLabel(179,72,50,16,"---",false,housegui)
guiLabelSetColor(priceLabel2,225,225,225)
guiLabelSetVerticalAlign(priceLabel2,"top")
guiLabelSetHorizontalAlign(priceLabel2,"left",false)
guiSetFont(priceLabel2,"default-bold-small")
streetLabel2 = guiCreateLabel(179,107,100,16,"---",false,housegui)
guiLabelSetColor(streetLabel2,225,225,225)
guiLabelSetVerticalAlign(streetLabel2,"top")
guiLabelSetHorizontalAlign(streetLabel2,"left",false)
guiSetFont(streetLabel2,"default-bold-small")
numberLabel2 = guiCreateLabel(187,90,50,16,"---",false,housegui)
guiLabelSetColor(numberLabel2,225,225,225)
guiLabelSetVerticalAlign(numberLabel2,"top")
guiLabelSetHorizontalAlign(numberLabel2,"left",false)
guiSetFont(numberLabel2,"default-bold-small")
sellPriceLabel = guiCreateLabel(137,123,65,15,"Sell Price: $",false,housegui)
guiLabelSetColor(sellPriceLabel,255,200,0)
guiLabelSetVerticalAlign(sellPriceLabel,"top")
guiLabelSetHorizontalAlign(sellPriceLabel,"left",false)
guiSetFont(sellPriceLabel,"default-bold-small")
sellPriceLabel2 = guiCreateLabel(204,123,50,16,"---",false,housegui)
guiLabelSetColor(sellPriceLabel2,225,225,225)
guiLabelSetVerticalAlign(sellPriceLabel2,"top")
guiLabelSetHorizontalAlign(sellPriceLabel2,"left",false)
guiSetFont(sellPriceLabel2,"default-bold-small")
buyButton = guiCreateButton(19,277,62,38,"Buy",false,housegui)
sellButton = guiCreateButton(150,277,62,38,"Sell",false,housegui)
closeButton = guiCreateButton(85,277,62,38,"Close",false,housegui)
lockButton = guiCreateButton(215,277,62,38,"(Un)Lock",false,housegui)
infiLabel2 = guiCreateLabel(15,142,276,15,"With home system you can buy your own house!",false,housegui)
guiLabelSetColor(infiLabel2,255,200,0)
guiLabelSetVerticalAlign(infiLabel2,"top")
guiLabelSetHorizontalAlign(infiLabel2,"left",false)
guiSetFont(infiLabel2,"default-bold-small")
HinfoLabel3 = guiCreateLabel(15,168,276,15,"When you got house, nobody cant buy or sell it,",false,housegui)
guiLabelSetColor(HinfoLabel3,255,200,0)
guiLabelSetVerticalAlign(HinfoLabel3,"top")
guiLabelSetHorizontalAlign(HinfoLabel3,"left",false)
guiSetFont(HinfoLabel3,"default-bold-small")
HinfoLabel4 = guiCreateLabel(15,182,276,15,"only you can!",false,housegui)
guiLabelSetColor(HinfoLabel4,255,200,0)
guiLabelSetVerticalAlign(HinfoLabel4,"top")
guiLabelSetHorizontalAlign(HinfoLabel4,"left",false)
guiSetFont(HinfoLabel4,"default-bold-small")
HinfoLabel5 = guiCreateLabel(15,210,276,15,"Buy or sell buttons wont gonna work, when you",false,housegui)
guiLabelSetColor(HinfoLabel5,255,200,0)
guiLabelSetVerticalAlign(HinfoLabel5,"top")
guiLabelSetHorizontalAlign(HinfoLabel5,"left",false)
guiSetFont(HinfoLabel5,"default-bold-small")
infoLabel6 = guiCreateLabel(15,227,276,15,"dont have engouht money, or you isn't the",false,housegui)
guiLabelSetColor(infoLabel6,255,200,0)
guiLabelSetVerticalAlign(infoLabel6,"top")
guiLabelSetHorizontalAlign(infoLabel6,"left",false)
guiSetFont(infoLabel6,"default-bold-small")
infoLabel7 = guiCreateLabel(14,245,276,15,"owner!",false,housegui)
guiLabelSetColor(infoLabel7,255,200,0)
guiLabelSetVerticalAlign(infoLabel7,"top")
guiLabelSetHorizontalAlign(infoLabel7,"left",false)
guiSetFont(infoLabel7,"default-bold-small")
guiSetVisible ( housegui, false )


function guiClicked()
	if (source == closeButton) then 
		guiSetVisible ( housegui, false )
		showCursor ( false )
	elseif ( source == buyButton ) then
		local housenumber = guiGetText ( numberLabel2 )
		triggerServerEvent ("HouseSystemBuyHouse",getLocalPlayer(),housenumber)
		guiSetVisible ( housegui, false )
		showCursor ( false )
	elseif ( source == sellButton ) then
		local housenumber = guiGetText ( numberLabel2 )
		triggerServerEvent ("HouseSystemSellHouse",getLocalPlayer(),housenumber)
		guiSetVisible ( housegui, false ) 
		showCursor ( false )
	elseif ( source == enterButton ) then
		local housenumber = guiGetText ( numberLabel2 )
	    triggerServerEvent ("HouseSystemEnterHouse",getLocalPlayer(),housenumber)
		guiSetVisible ( housegui, false ) 
		showCursor ( false )
	elseif (source == closeButton2) then 
		guiSetVisible ( createHouseWindow, false )
		showCursor ( false )
		unbindKey ( "mouse2","down", showCursor12 )
		guiSetInputEnabled ( false )
	elseif (source == getPickupPosButton) then 
		local x,y,z = getElementPosition ( getLocalPlayer())
		guiSetText ( pickupXEdit, x )
		guiSetText ( pickupYEdit, y )
		guiSetText ( pickupZEdit, z )
	elseif (source == getMarkerPosButton) then 
		local x,y,z = getElementPosition ( getLocalPlayer())
		guiSetText ( markerXEdit, x )
		guiSetText ( markerYEdit, y )
		guiSetText ( markerZEdit, z )
	elseif (source == tryInteriorButton) then 
		local intNumber = guiGetText ( interiorIDEdit )
		triggerServerEvent ( "tryInterior", getLocalPlayer(), intNumber )
	elseif (source == createHouseButton) then 
		local intNumber = guiGetText ( interiorIDEdit )
		local price = guiGetText (priceEdit)
		local sellprice = guiGetText (sellPriceEdit)
		local street = guiGetText (streetEdit)
		local intx = guiGetText (markerXEdit)
		local inty = guiGetText (markerYEdit)
		local intz = guiGetText (markerZEdit)
		local pickupx = guiGetText (pickupXEdit)
		local pickupy = guiGetText (pickupYEdit)
		local pickupz = guiGetText (pickupZEdit)
		if not ( intNumber == "" ) or ( price == "" ) or ( sellprice == "" ) or ( street == "" ) or ( intx == "" ) or ( inty == "" ) or ( intz == "" ) or ( pickupx == "" ) or ( pickupy == "" ) or ( pickupz == "" ) then
		triggerServerEvent ( "createhome", getLocalPlayer(), intNumber, price, sellprice, street, intx, inty, intz, pickupx, pickupy, pickupz )
		end
	elseif ( source == lockButton ) then
		local housenumber = guiGetText ( numberLabel2 )
		triggerServerEvent ("houseSystemLockHouse",getLocalPlayer(),housenumber)
	end
end
addEventHandler ( "onClientGUIClick", getRootElement(), guiClicked)


addEvent ("viewHouseGUIwindow",true)
addEventHandler ("viewHouseGUIwindow",getRootElement(),
function(owner,price,housenumber,sellprice,street)
  if (source == getLocalPlayer()) then
    guiSetText (ownerLabel2,owner)
    guiSetText (priceLabel2,price)
    guiSetText (numberLabel2,housenumber)
	guiSetText (sellPriceLabel2,sellprice)
	guiSetText (streetLabel2,street)
    guiSetVisible (housegui,true)
    showCursor (true)
  end
end)


-- Create Home 


createHouseWindow = guiCreateWindow(465,162,317,419,"House System Create House",false)
image = guiCreateStaticImage(19,22,278,75,"housesystem.png",false,createHouseWindow)
interiorIDLabel = guiCreateLabel(29,104,78,15,"Interior ID",false,createHouseWindow)
guiLabelSetColor(interiorIDLabel,255,255,255)
guiLabelSetVerticalAlign(interiorIDLabel,"top")
guiLabelSetHorizontalAlign(interiorIDLabel,"left",false)
guiSetFont(interiorIDLabel,"default-bold-small")
priceLabel = guiCreateLabel(29,125,78,17,"Price",false,createHouseWindow)
guiLabelSetColor(priceLabel,255,255,255)
guiLabelSetVerticalAlign(priceLabel,"top")
guiLabelSetHorizontalAlign(priceLabel,"left",false)
guiSetFont(priceLabel,"default-bold-small")
interiorIDEdit = guiCreateEdit(102,103,142,18,"",false,createHouseWindow)
tryInteriorButton = guiCreateButton(250,103,45,18,"Try!",false,createHouseWindow)
sellPriceLabel = guiCreateLabel(29,148,78,17,"Sell Price",false,createHouseWindow)
guiLabelSetColor(sellPriceLabel,255,255,255)
guiLabelSetVerticalAlign(sellPriceLabel,"top")
guiLabelSetHorizontalAlign(sellPriceLabel,"left",false)
guiSetFont(sellPriceLabel,"default-bold-small")
streetLabel = guiCreateLabel(29,169,78,17,"Street",false,createHouseWindow)
guiLabelSetColor(streetLabel,255,255,255)
guiLabelSetVerticalAlign(streetLabel,"top")
guiLabelSetHorizontalAlign(streetLabel,"left",false)
guiSetFont(streetLabel,"default-bold-small")
pickupXLabel = guiCreateLabel(29,228,78,17,"Pos X",false,createHouseWindow)
guiLabelSetColor(pickupXLabel,255,255,255)
guiLabelSetVerticalAlign(pickupXLabel,"top")
guiLabelSetHorizontalAlign(pickupXLabel,"left",false)
guiSetFont(pickupXLabel,"default-bold-small")
pickupLabel = guiCreateLabel(20,203,78,17,"Pickup",false,createHouseWindow)
guiLabelSetColor(pickupLabel,255,255,255)
guiLabelSetVerticalAlign(pickupLabel,"top")
guiLabelSetHorizontalAlign(pickupLabel,"left",false)
guiSetFont(pickupLabel,"default-bold-small")
pickupZLabel = guiCreateLabel(29,269,78,17,"Pos Z",false,createHouseWindow)
guiLabelSetColor(pickupZLabel,255,255,255)
guiLabelSetVerticalAlign(pickupZLabel,"top")
guiLabelSetHorizontalAlign(pickupZLabel,"left",false)
guiSetFont(pickupZLabel,"default-bold-small")
pickupYLabel = guiCreateLabel(29,249,78,17,"Pos Y",false,createHouseWindow)
guiLabelSetColor(pickupYLabel,255,255,255)
guiLabelSetVerticalAlign(pickupYLabel,"top")
guiLabelSetHorizontalAlign(pickupYLabel,"left",false)
guiSetFont(pickupYLabel,"default-bold-small")
MarkerLabel = guiCreateLabel(19,295,78,17,"Marker",false,createHouseWindow)
guiLabelSetColor(MarkerLabel,255,255,255)
guiLabelSetVerticalAlign(MarkerLabel,"top")
guiLabelSetHorizontalAlign(MarkerLabel,"left",false)
guiSetFont(MarkerLabel,"default-bold-small")
markerXLabel = guiCreateLabel(28,316,78,17,"Pos X",false,createHouseWindow)
guiLabelSetColor(markerXLabel,255,255,255)
guiLabelSetVerticalAlign(markerXLabel,"top")
guiLabelSetHorizontalAlign(markerXLabel,"left",false)
guiSetFont(markerXLabel,"default-bold-small")
markerYLabel = guiCreateLabel(29,336,78,17,"Pos Y",false,createHouseWindow)
guiLabelSetColor(markerYLabel,255,255,255)
guiLabelSetVerticalAlign(markerYLabel,"top")
guiLabelSetHorizontalAlign(markerYLabel,"left",false)
guiSetFont(markerYLabel,"default-bold-small")
markerZLabel = guiCreateLabel(29,357,78,17,"Pos Z",false,createHouseWindow)
guiLabelSetColor(markerZLabel,255,255,255)
guiLabelSetVerticalAlign(markerZLabel,"top")
guiLabelSetHorizontalAlign(markerZLabel,"left",false)
guiSetFont(markerZLabel,"default-bold-small")
priceEdit = guiCreateEdit(102,125,142,18,"",false,createHouseWindow)
sellPriceEdit = guiCreateEdit(102,147,142,18,"",false,createHouseWindow)
streetEdit = guiCreateEdit(102,169,142,18,"",false,createHouseWindow)
pickupXEdit = guiCreateEdit(102,227,142,18,"",false,createHouseWindow)
pickupYEdit = guiCreateEdit(102,248,142,18,"",false,createHouseWindow)
pickupZEdit = guiCreateEdit(102,269,142,18,"",false,createHouseWindow)
markerXEdit = guiCreateEdit(102,315,142,18,"",false,createHouseWindow)
markerYEdit = guiCreateEdit(102,336,142,18,"",false,createHouseWindow)
markerZEdit = guiCreateEdit(102,357,142,18,"",false,createHouseWindow)
getPickupPosButton = guiCreateButton(250,271,45,18,"Get!",false,createHouseWindow)
getMarkerPosButton = guiCreateButton(250,358,45,18,"Get!",false,createHouseWindow)
createHouseButton = guiCreateButton(227,392,60,18,"Create!",false,createHouseWindow)
closeButton2 = guiCreateButton(156,392,60,18,"Close",false,createHouseWindow)
guiSetVisible ( createHouseWindow, false )

function showWindow (commandName)	
	guiSetVisible ( createHouseWindow, true )
	showCursor ( true )
	bindKey ( "mouse2","down", showCursor12 )
end
addEvent ( "showWindow", true )
addEventHandler ( "showWindow", getRootElement(), showWindow )


function showCursor12 ()
	if ( isCursorShowing() == true ) then
	showCursor ( false )
	else
	showCursor ( true )
	end
end

addEventHandler ("onClientMouseEnter",getRootElement(),
function ()
if source == createHouseWindow or source == streetEdit then
 guiSetInputEnabled ( true )
end
end)

addEventHandler ("onClientMouseLeave",getRootElement(),
function ()
if source == createHouseWindow or source == streetEdit then
 guiSetInputEnabled ( false )
end
end)



